- name: Gather Facts for Cisco ASA
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  tasks:

    - name: Get config for Cisco ASA devices
      cisco.asa.asa_facts:
        gather_subset: all

    - name: Gather legacy and resource facts
      cisco.asa.asa_facts:
        gather_subset: all

    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
        msg: "Output of the all the variables: "
        msg: "{{hostvars[inventory_hostname]}}"